version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend_api
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./nexus-backend:/app/nexus-backend
    command: npm run dev

volumes:
  pgdata:
